name: Auto Work

on:
  schedule:
    - cron: "0 */12 * * *"
      
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install Dependencies
        run: npm i
      - name: Auto Work
        run: npm run work
